model:
  name: Qwen/Qwen2.5-VL-3B-Instruct
  dtype: bfloat16
  quant: int4  # use bitsandbytes
lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules:
    - q_proj
    - k_proj
    - v_proj
    - o_proj
    - gate_proj
    - up_proj
    - down_proj
